import { useEffect, useState } from 'react';

export const useGetLanguage = ({ lang }) => {
    const [currentLanguage, setCurrentLanguage] = useState({ code: '', string: {} });

    const langList = [
        {
            code: 'en',

            string: {
                option_not_available: 'Option not available',
                replace: 'Replace',
                your_limit: 'Your limit',
                create_a_color: 'Create a color',
                create_a_brand: 'Create a brand',
                yes: 'Yes',
                no: 'No',
                show_in_market: 'Available in market',
                unlimited: 'Unlimited',
                call_back: 'Callback',
                size_table: 'Size table',
                attached_to_the_product_deletion_is_not_possible: 'Attached to the product. Deletion not possible',
                leave_the_comment: 'Leave a comment',
                change_status: 'Change status',
                change: 'Change',
                order_history: 'Order history',
                delivery_address: 'Delivery address',
                company: 'Company',
                total_final_price: 'Total final price',
                total_quantity: 'Total quantity',
                quantity: 'Quantity',
                final_price: 'Final price',
                create_new_model: 'Create new model',
                click_to_choose: 'Click to choose',
                file_more_then_ten_mbd: 'File larger than 10MB',
                wrong_file_format: 'Incorrect file format',
                image: 'Image',
                video: 'Video',
                add_image: 'Add image',
                examples: 'Examples',
                add_models_before: 'Add models first',
                types: 'Types',
                date_available: 'Date available',
                product_type: 'Product type',
                items: 'items',
                find: 'Find',
                customers: 'Customers',
                customer: 'Customer',
                delivery: 'Delivery',
                orders: 'Orders',
                order: 'Order',
                brands: 'Brands',
                brand: 'Brand',
                list: 'List',
                inventory: 'Inventory',
                market: 'Market',
                store_with_this_code_is_registered: 'Store with this code is registered',
                category_with_this_code_is_registered: 'Category with this code is registered',
                user_with_this_email_is_registered: 'User with this email is registered',
                brand_with_this_code_is_registered: 'Brand with this code is registered',
                color_with_this_code_is_registered: 'Color with this code is already created',
                size_with_this_code_is_registered: 'Size with this code is already created',
                promo_with_this_code_is_registered: 'Promo tag with this code is already created',
                model_with_this_vendor_code_is_registered: 'Model with this vendor code is already created',
                create_user: 'Create user',
                edit_user: 'Edit user',
                back: 'Back',
                create_new_user: 'Create new user',
                should_contains_1_character_lowercase_1_character_uppercase_1_digit_6_to_12_characters:
                    'Must contain 1 lowercase character, 1 uppercase character, 1 digit, 6 to 12 characters',
                active: 'Active',
                activate: 'Activate',
                deactivate: 'Deactivate',
                code_must_be_unique: 'Code must be unique',
                staff: 'Staff',
                store_address: 'Store address',
                store_description: 'Store description',
                product_settings: 'Product settings',
                product_types: 'Product types',
                store_security: 'Store security',
                private_store: 'Private store',
                store_key: 'Store key',
                share_product_link: 'Share product link',
                prices: 'Prices',
                search_by_sku: 'Search by SKU',
                functions_settings: 'Functions settings',
                product_image_settings: 'Product image settings',
                logo: 'Logo',
                store_image: 'Store image',
                width: 'Width',
                height: 'Height',
                crop_width: 'Crop width',
                crop_height: 'Crop height',
                settings: 'Settings',
                images_settings: 'Image settings',
                options: 'Options',
                add_new: 'Add new',
                manager: 'Manager',
                owner: 'Owner',
                start_date_operation: 'Start date operation',
                currency: 'Currency',
                default_language: 'Default language',
                supported_languages: 'Supported languages',
                language: 'Language',
                postal_code: 'Postal code',
                store_state_province: 'Store state/province',
                store_phone: 'Store phone',
                store_email: 'Store email',
                store_code: 'Store code',
                store_name: 'Store name',
                store_city: 'Store city',
                store_country: 'Store country',
                edit_store: 'Edit store',
                edit: 'Edit',
                create_store: 'Create store',
                store: 'Store',
                stores_management: 'Stores management',
                users: 'Users',
                user: 'User',
                main: 'Main',
                create_new_store: 'Create new store',
                download_image: 'Download image',
                download_logo: 'Download logo',
                search: 'Search',
                approve: 'Approve',
                clear_filters: 'Clear filters',
                clear: 'Clear',
                filter: 'Filter',
                nothing_was_found: 'Nothing was found',
                stores: 'Stores',
                favorites: 'Favorites',
                login: 'Login',
                welcome_to_Sales_Nest_to_get_started_login: 'Welcome to Sales Nest, to get started, login!',
                wrong_login_or_password: 'Wrong login or password',
                cart: 'Cart',
                vendor_code: 'Vendor code',
                color: 'Color',
                price: 'Price',
                logout: 'Logout',
                submit: 'Submit',
                ukraine: 'Ukraine',
                czechia: 'Czechia',
                poland: 'Poland',
                description: 'Description',
                first_name: 'First name',
                last_name: 'Last name',
                phone_number: 'Phone number',
                city: 'City',
                email: 'Email',
                password: 'Password',
                confirm_password: 'Confirm password',
                do_want_to_logout: 'Do you really want to logout?',
                status: 'Status',
                ordered_date: 'Ordered date',
                do_you_want_to_delete_promo_label: 'Do you want to delete the promo tag?',
                do_you_want_to_delete_color: 'Do you want to delete the color?',
                do_you_want_to_delete_size: 'Do you want to delete the size?',
                do_you_want_to_delete_store: 'Do you want to delete the store?',
                do_you_want_to_delete_user: 'Do you want to delete the user?',
                do_you_want_to_delete_product: 'Do you want to delete the product?',
                do_you_want_to_delete_brand: 'Do you want to delete the brand?',
                do_you_want_to_delete_model: 'Do you want to delete the model?',
                do_you_want_to_delete_category: 'Do you want to delete the category?',
                cancel: 'Cancel',
                enter_password: 'Enter password',
                enter_email: 'Enter email',
                enter_valid_email: 'Enter a valid email',
                password_length_min_8_symbols: 'Password length minimum 8 symbols',
                passwords_do_not_match: 'Passwords do not match',
                my_profile: 'My profile',
                country: 'Country',
                customers_list: 'Customers list',
                categories: 'Categories',
                colors: 'Colors',
                sizes: 'Sizes',
                full_name: 'Full name',
                size: 'Size',
                save: 'Save',
                saved: 'Saved',
                updated: 'Updated',
                created: 'Created',
                deleted: 'Deleted',
                contacts: 'Contacts',
                name: 'Name',
                create: 'Create',
                update: 'Update',
                order_priority: 'Order priority',
                models: 'Models',
                model: 'Model',
                add: 'Add',
                delete: 'Delete',
                create_category: 'Create category',
                choose_or_create_a_category: 'Choose or create a category',
                add_category: 'Add category',
                label: 'Label',
                code: 'Code',
                products: 'Products',
                processed: 'Processed',
                ordered: 'Ordered',
                delivered: 'Delivered',
                refunded: 'Refunded',
                canceled: 'Canceled',
                loading: 'Loading',
                available: 'Available',
                load_more: 'Load more',
                promo: 'Promo',
                available_in_browser: 'Available in browser',
                out_of: 'out of',
                photo: 'Photo',
                analytics: 'Analytics',
                required_field: 'required field',
                code_latin_symbols: 'Code must consist of Latin characters',
                code_latin_symbols_numbers: 'Code must consist of Latin characters or numbers',
                code_3_latin_symbols: 'Code must consist of at least 3 Latin characters or numbers',
                input_correct_code: 'Enter a correct code',
                min_6_symbols: 'Minimum 6 characters',
                max_12_symbols: 'Maximum 12 characters',
                min_1_number_uppercase: 'Minimum 1 digit, 1 uppercase letter',
                max_60_symbols: 'Maximum 60 characters',
                max_images: 'Max images',
                add_or_drop_images: 'Add or Drop Images',
            },
        },
        {
            code: 'ua',

            string: {
                option_not_available: 'Опцiя недоступна',
                replace: 'Змiнити',
                your_limit: 'Ваш лiмiт',
                create_a_color: 'Створiть колiр',
                create_a_brand: 'Створiть бренд',
                yes: 'Так',
                no: 'Нi',
                show_in_market: 'Доступний на платформi',
                unlimited: 'Необмежено',
                call_back: 'Зворотнiй зв`язок',
                size_table: 'Таблиця розмірів',
                attached_to_the_product_deletion_is_not_possible: 'Прикріплений до продукту. Видалення неможливо',
                leave_the_comment: 'Залишити коментар',
                change_status: 'Змiнити статус',
                change: 'Змiнити',
                order_history: 'Iсторiя замовлення',
                delivery_address: 'Адреса Поштового Вiддiлення',
                company: 'Компанiя',
                total_final_price: 'Загальна сума',
                total_quantity: 'Загальна кiлькiсть',
                quantity: 'Кiлькiсть',
                final_price: 'Сумма',
                create_new_model: 'Створити нову модель',
                click_to_choose: 'натиснiть щоб обрати',
                file_more_then_ten_mbd: 'Файл бiльше 10MB',
                wrong_file_format: 'Невiрний формат файлу',
                image: 'Зображення',
                video: 'Вiдео',
                add_image: 'Додати зображення',
                examples: 'Приклади',
                add_models_before: 'Спершу додайте моделi',
                types: 'Види',
                date_available: 'Дата наявностi',
                product_type: 'Тип продукта',
                items: 'одиниць',
                find: 'Знайти',
                customers: 'Клієнти',
                customer: 'Замовник',
                delivery: 'Доставка',
                orders: 'Замовлення',
                order: 'Замовлення',
                brands: 'Бренди',
                brand: 'Бренд',
                list: 'Список',
                inventory: 'Iнвентар',
                market: 'Ринок',
                store_with_this_code_is_registered: 'Магазин з такою поштою зареєстрований',
                category_with_this_code_is_registered: 'Категорiя з таким кодом зареєстрована',
                user_with_this_email_is_registered: 'Користувач з такою поштою зареєстрований',
                brand_with_this_code_is_registered: 'Бренд з таким кодом зареєстрований',
                color_with_this_code_is_registered: 'Колiр з таким кодом вже створено',
                size_with_this_code_is_registered: 'Розмiр з таким кодом вже створено',
                promo_with_this_code_is_registered: 'Промо тег з таким кодом вже створено',
                model_with_this_vendor_code_is_registered: 'Модель з таким артикулом вже створена',
                create_user: 'Створити користувача',
                edit_user: 'Редагувати користувача',
                back: 'Назад',
                create_new_user: 'Створити нового користувача',
                should_contains_1_character_lowercase_1_character_uppercase_1_digit_6_to_12_characters:
                    'Має містити 1 символ у нижньому регістрі, 1 символ у верхньому регістрі, 1 цифру, від 6 до 12 символів',
                active: 'Активований',
                activate: 'Активувати',
                deactivate: 'Деактивувати',
                code_must_be_unique: 'Код повинен бути унiкальним',
                staff: 'Персонал',
                store_address: 'Адреса магазину',
                store_description: 'Опис магазину',
                product_settings: 'Налаштування продукцii',
                product_types: 'Типи товару',
                store_security: 'Безпека магазину',
                private_store: 'Приватний магазин',
                store_key: 'Ключ магазину',
                share_product_link: 'Подiлитися посиланням товару',
                prices: 'Цiни',
                search_by_sku: 'Пошук за артикулом',
                functions_settings: 'Налаштування функцiоналу',
                product_image_settings: 'Налаштування зображення продукту',
                logo: 'Логотип',
                store_image: 'Зображення магазину',
                width: 'Ширина',
                height: 'Висота',
                crop_width: 'Обрiзати ширину',
                crop_height: 'Обрiзати висоту',
                settings: 'Налаштування',
                images_settings: 'Налаштування зображень',
                options: 'Опції',
                add_new: 'Додати нового',
                manager: 'Менеджер',
                owner: 'Власник',
                start_date_operation: 'Дата початку роботи',
                currency: 'Валюта',
                default_language: 'Мова по замовчуванню',
                supported_languages: 'Мови магазину',
                language: 'Мова',
                postal_code: 'Поштовий iндекс',
                store_state_province: 'Штат/область магазину',
                store_phone: 'Телефон магазину',
                store_email: 'Електронна пошта магазину',
                store_code: 'Код магазину',
                store_name: 'Назва магазину',
                store_city: 'Мiсто магазину',
                store_country: 'Країна магазину',
                edit_store: 'Редагувати магазин',
                edit: 'Редагувати',
                create_store: 'Створити магазин',
                store: 'Магазин',
                stores_management: 'Керування магазинами',
                users: 'Користувачi',
                user: 'Користувач',
                main: 'Головна',
                create_new_store: 'Створити новий магазин',
                download_image: 'Завантажити фото',
                download_logo: 'Завантажити логотип',
                search: 'Знайти',
                approve: 'Пiдтвердити',
                clear_filters: 'Очистити фільтри',
                clear: 'Очистити',
                filter: 'Фільтр',
                nothing_was_found: 'Нічого не знайдено',
                stores: 'Магазини',
                favorites: 'Уподобане',
                login: 'Вхід',
                welcome_to_Sales_Nest_to_get_started_login:
                    'Ласкаво просимо до Sales Nest, щоб почати роботу, увійдіть!',
                wrong_login_or_password: 'Неправильний логін або пароль',
                cart: 'Кошик',
                vendor_code: 'Артикул',
                color: 'Колір',
                price: 'Ціна',
                logout: 'Вийти',
                submit: 'Підтвердити',
                ukraine: 'Україна',
                czechia: 'Чехія',
                poland: 'Польща',
                description: 'Опис',
                first_name: `Ім'я`,
                last_name: 'Прізвище',
                phone_number: 'Номер телефону',
                city: 'Місто',
                email: 'Пошта',
                password: 'Пароль',
                confirm_password: 'Підтвердити пароль',
                do_want_to_logout: 'Ви дійсно хочете залишити обліковий запис?',
                status: 'Статус',
                ordered_date: 'Дата замовлення',
                do_you_want_to_delete_promo_label: 'Хочете видалити промо тег?',
                do_you_want_to_delete_color: 'Хочете видалити колiр?',
                do_you_want_to_delete_size: 'Хочете видалити розмiр?',
                do_you_want_to_delete_store: 'Хочете видалити магазин?',
                do_you_want_to_delete_user: 'Хочете видалити кориистувача?',
                do_you_want_to_delete_product: 'Хочете видалити товар?',
                do_you_want_to_delete_brand: 'Хочете видалити бренд?',
                do_you_want_to_delete_model: 'Хочете видалити модель?',
                do_you_want_to_delete_category: 'Хочете видалити категорiю?',
                cancel: 'Скасувати',
                enter_password: 'Введіть пароль',
                enter_email: 'Введіть електронну пошту',
                enter_valid_email: 'Введіть дійсну електронну пошту',
                password_length_min_8_symbols: 'Довжина пароля не менше 8 символів',
                passwords_do_not_match: 'Паролі не збігаються',
                my_profile: 'Профіль',
                country: 'Країна',
                customers_list: 'Список клієнтів',
                categories: 'Категорії',
                colors: 'Кольори',
                sizes: 'Розміри',
                full_name: `Повне ім'я`,
                size: 'Розмір',
                save: 'Зберегти',
                saved: 'Сбережено',
                updated: 'Оновлено',
                created: 'Створено',
                deleted: 'Видалено',
                contacts: 'Контакти',
                name: 'Назва',
                create: 'Створити',
                update: 'Оновити',
                order_priority: 'Пріоритет',
                models: 'Моделі',
                model: 'Модель',
                add: 'Додати',
                delete: 'Видалити',
                create_category: 'Створити категорiю',
                choose_or_create_a_category: 'Оберiть або створiть категорiю',
                add_category: 'Додати категорію',
                label: 'Позначка',
                code: 'Код',
                products: 'Товар',
                processed: 'Обробелено',
                ordered: 'Замовлено',
                delivered: 'Доставлено',
                refunded: 'Повернено',
                canceled: 'Скасовано',
                loading: 'Завантаження',
                available: 'В наявностi',
                load_more: 'Завантажити більше',
                promo: 'Промо',
                available_in_browser: 'Доступний для браузера',
                out_of: 'з',
                photo: 'Фото',
                analytics: 'Аналiтика',
                required_field: 'Обов`язкове поле',
                code_latin_symbols: 'Код має складатися з латинських символів',
                code_latin_symbols_numbers: 'Код має складатися з латинських символів aбо цифр',
                code_3_latin_symbols: 'Код має складатися щонайменше з 3 латинських символів або цифр',
                input_correct_code: 'Введiть коректний код',
                min_6_symbols: 'Мiнiмум 6 символiв',
                max_12_symbols: 'Максимум 12 символiв',
                min_1_number_uppercase: 'Мiнiмум 1 цифра 1 велика буква',
                max_60_symbols: 'Максимально 60 символiв',
                max_images: 'Максимально зображень',
                add_or_drop_images: 'Додай або перетягни зображення',
            },
        },
    ];

    useEffect(() => {
        setCurrentLanguage(langList.find(({ code }) => code === lang));
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [lang]);

    return { currentLanguage };
};
