import { useEffect, useState } from 'react';

export const useGetLanguage = ({ lang }) => {
    const [currentLanguage, setCurrentLanguage] = useState({ code: '', string: {} });

    const langList = [
        {
            code: 'ua',

            string: {
                items: 'одиниць',
                find: 'Знайти',
                customers: 'Клієнти',
                orders: 'Замовлення',
                brands: 'Бренди',
                list: 'Список',
                inventory: 'Iнвентар',
                market: 'Ринок',
                sales: '',
                user_with_this_email_is_registered: 'Користувач з такою поштою зареєстрований',
                create_user: 'Створити користувача',
                edit_user: 'Редагувати користувача',
                back: 'Назад',
                create_new_user: 'Створити нового користувача',
                should_contains_1_character_lowercase_1_character_uppercase_1_digit_6_to_12_characters:
                    'Має містити 1 символ у нижньому регістрі, 1 символ у верхньому регістрі, 1 цифру, від 6 до 12 символів',
                active: 'Активований',
                code_must_be_unique: 'Код повинен бути унiкальним',
                staff: 'Персонал',
                store_address: 'Адреса магазину',
                store_description: 'Опис магазину',
                product_settings: 'Налаштування продукцii',
                product_types: 'Типи товару',
                store_security: 'Безпека магазину',
                private_store: 'Приватний магазин',
                store_key: 'Ключ магазину',
                share_product_link: 'Подiлитися посиланням товару',
                prices: 'Цiни',
                search_by_sku: 'Пошук за артикулом',
                functions_settings: 'Налаштування функцiоналу',
                product_image_settings: 'Налаштування зображення продукту',
                logo: 'Логотип',
                store_image: 'Зображення магазину',
                width: 'Ширина',
                height: 'Висота',
                crop_width: 'Обрiзати ширину',
                crop_height: 'Обрiзати висоту',
                settings: 'Налаштування',
                images_settings: 'Налаштування зображень',
                options: 'Опції',
                add_new: 'Додати нового',
                manager: 'Менеджер',
                owner: 'Власник',
                start_date_operation: 'Дата початку роботи',
                currency: 'Валюта',
                default_language: 'Мова по замовчуванню',
                supported_languages: 'Мови магазину',
                postal_code: 'Поштовий iндекс',
                store_state_province: 'Штат/область магазину',
                store_phone: 'Телефон магазину',
                store_email: 'Електронна пошта магазину',
                store_code: 'Код магазину',
                store_name: 'Назва магазину',
                store_city: 'Мiсто магазину',
                store_country: 'Країна магазину',
                edit_store: 'Редагувати магазин',
                edit: 'Редагувати',
                create_store: 'Створити магазин',
                store: 'Магазин',
                stores_management: 'Керування магазинами',
                users: 'Користувачi',
                user: 'Користувач',
                main: 'Головна',
                create_new_store: 'Створити новий магазин',
                download_image: 'Завантажити фото',
                download_logo: 'Завантажити логотип',
                // languages: 'Мови',
                // back_to_stores: 'Повернутися до магазинiв',
                // ok: 'Ок',
                // search: 'Знайти',
                // language: 'Мова',
                // wrong_key: 'Неправильний ключ!',
                approve: 'Пiдтвердити',
                // ready: 'Готово',
                clear_filters: 'Очистити фільтри',
                clear: 'Очистити',
                filter: 'Фільтр',
                nothing_was_found: 'Нічого не знайдено',
                stores: 'Магазини',
                // catalog: 'Каталог',
                // polish: 'Польська',
                // czech: 'Чеська',
                // russian: 'Російська',
                // ukrainian: 'Українська',
                // english: 'Англійська',
                // find_store_by_name: 'Знайти магазин по назві',
                favorites: 'Уподобане',
                // my_stores: 'Мої магазини',
                login: 'Вхід',
                welcome_to_Cocktail_to_get_started_login: 'Ласкаво просимо до Cocktail, щоб почати роботу, увійдіть!',
                // register: 'Зареєструватися',
                wrong_login_or_password: 'Неправильний логін або пароль',
                // forgot_password: 'Забули пароль?',
                cart: 'Кошик',
                vendor_code: 'Артикул',
                // color: 'Колір',
                // available_sizes: 'Доступні розміри',
                // go_to_details: 'Перейти до деталей',
                // remove: 'Видалити',
                // price: 'Ціна',
                // total_price: 'Загальна сума',
                // total_quantity: 'Загальна кількість',
                // add_product_sizes: 'Додайте розміри продукту',
                // gallery: 'Галерея',
                // admin: 'Адмін',
                logout: 'Вийти',
                submit: 'Підтвердити',
                ukraine: 'Україна',
                czechia: 'Чехія',
                // italy: 'Італія',
                // kazakhstan: 'Казахстан',
                poland: 'Польща',
                // turkey: 'Туреччина',
                description: 'Опис',
                // added: 'Додано',
                // add_to: 'Додати до',
                // confirm_order: 'Підтвердити замовлення',
                // personal_data: 'Особисті дані',
                first_name: `Ім'я`,
                last_name: 'Прізвище',
                // receiver_first_name: `Ім'я одержувача`,
                // receiver_last_name: 'Прізвище одержувача',
                // receiver_phone_number: 'Номер телефону одержувача',
                phone_number: 'Номер телефону',
                city: 'Місто',
                email: 'Пошта',
                password: 'Пароль',
                confirm_password: 'Підтвердити пароль',
                // company_name: 'Назва компанії',
                // already_registered: 'Вже зареєстровані',
                do_want_to_logout: 'Ви дійсно хочете залишити обліковий запис?',
                // delivery_information: 'Інформація про доставку',
                // additional_information: 'Додаткова інформація',
                // post_office: 'Адреса поштового відділення',
                // comments: 'Коментарі',
                // status: 'Статус',
                // ordered_date: 'Дата замовлення',
                // delete_item: 'Видалити замовлення',
                do_you_want_to_delete_item: 'Хочете видалити замовлення?',
                do_you_want_to_delete_store: 'Хочете видалити магазин?',
                do_you_want_to_delete_user: 'Хочете видалити кориистувача?',
                do_you_want_to_delete_product: 'Хочете видалити товар?',
                cancel: 'Скасувати',
                // confirm: 'Підтвердити',
                // do_you_want_to_confirm_order: 'Хочете підтвердити замовлення?',
                // order: 'Замовлення',
                // clear_cart: 'Очистити кошик',
                // do_you_want_to_clear_cart: 'Бажаєте очистити кошик?',
                // clear_favorites: 'Очистити уподобане',
                // do_you_want_to_clear_favorites: 'Бажаєте очистити уподобане?',
                // promo_code: 'Промокод',
                enter_password: 'Введіть пароль',
                enter_email: 'Введіть електронну пошту',
                enter_valid_email: 'Введіть дійсну електронну пошту',
                password_length_min_8_symbols: 'Довжина пароля не менше 8 символів',
                passwords_do_not_match: 'Паролі не збігаються',
                // enter_first_name: `Введіть ім'я`,
                // enter_last_name: 'Введіть прізвище',
                // enter_phone_number: 'Введіть номер телефону',
                // login_to_order: 'Увійдіть, щоб замовити',
                // my_orders: 'Мої замовлення',
                my_profile: 'Профіль',
                // price_per_item: 'Ціна за шт.',
                // country: 'Країна',
                // e_a: 'од.',
                // reset_password: 'Скинути пароль',
                // close: 'Закрити',
                // please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                //     'Будь ласка, введіть адресу електронної пошти. Ви отримаєте електронною поштою посилання для створення нового пароля.',
                // an_email_with_a_link_has_been_sent_to_your_email:
                //     'На Вашу електронну пошту надіслано листа з посиланням',
                // user_with_this_email_not_found: 'Користувача з такою електронною поштою не знайдено',
                // find_by_vendor_code: 'Знайти модель за артикулом',
                // //ADMIN
                // orders_list: 'Список замовлень',
                customers_list: 'Список клієнтів',
                // products_list: 'Список Товару',
                // products_QR_list: 'Список QR Товару',
                // products_options: 'Опції продуктів',
                // add_user: 'Додати користувача',
                // dashboard: 'Аналітика',
                categories: 'Категорії',
                colors: 'Кольори',
                sizes: 'Розміри',
                // variants: 'Класифікації',
                // id: '№',
                full_name: `Повне ім'я`,
                // actions: 'Дії',
                size: 'Розмір',
                // quantity: 'Кількість',
                save: 'Зберегти',
                saved: 'Сбережено',
                updated: 'Оновлено',
                created: 'Створено',
                deleted: 'Видалено',
                // pledge: 'Застава',
                contacts: 'Контакти',
                // name: 'Назва',
                // completeness: 'Повнота',
                // add_models: 'Додати моделі',
                // add_images: 'Додайте зображення',
                // add_sizes: 'Додайте розміри',
                // completed: 'Виконано',
                // available: 'В наявності',
                create: 'Створити',
                // product_data: 'Дані продукту',
                // update: 'Оновити',
                // order_priority: 'Пріоритет',
                models: 'Моделі',
                // add: 'Додати',
                // add_product_to_add_sizes: 'Додати дані продукту для додавання розмірів',
                // add_product_to_add_categories: 'Додайте дані продукту, щоб додати категорії',
                // add_product_to_add_models: 'Додайте дані продукту, щоб додати моделі',
                // vendor_code_must_be_unique: 'Артикул має бути унікальним',
                delete: 'Видалити',
                // categories_options: 'Параметри категорій',
                // new_category_name: 'Назва категорії',
                // new_category_code: 'Код категорії',
                // selected_category: 'Вибрана категорія',
                // add_category_name: 'Додайте назву категорії',
                // root: 'Корінь',
                // add_category_code: 'Додайте код категорії',
                // colors_options: 'Варіанти кольорів',
                // add_color: 'Додати колір',
                // edit_color: 'Редагувати колір',
                // add_color_name: 'Додайте назву кольору',
                // option_name: 'Назва опції',
                // color_code: 'Код кольору',
                // color_name: 'Назва кольору',
                // available_colors: 'Доступні кольори',
                // label: 'Позначка',
                // code: 'Код',
                // sizes_options: 'Варіанти розмірів',
                // edit_size: 'Редагувати розмір',
                // add_size: 'Додайте розмір',
                // size_code: 'Код розміру',
                // size_name: 'Назва розміру',
                // add_size_code: 'Додайте код розміру',
                // add_size_name: 'Додайте назву розміру',
                // variants_options: 'Варіанти класифікацій',
                // add_variant_by_color: 'Додати класифікацію за кольором',
                // available_variants: 'Доступні класифікації',
                // option_code: 'Код опції',
                // add_option_code: 'Додайте код опції',
                // option_value: 'Значення опції',
                // change_password: 'Змінити пароль',
                // new_password: 'Новий пароль',
                // product_create: 'Створення продукту',
                // details: 'Деталі',
                // change_status: 'Змінити статус',
                // do_you_want_to_change_order_status: 'Бажаєте змінити статус замовлення?',
                // leave_the_comment: 'Залишити коментар',
                // order_history: 'Історія Замовлення',
                products: 'Товар',
                // //order status
                // processed: 'Зроблений',
                // ordered: 'Замовлений',
                // delivered: 'Доставлено',
                // refunded: 'Повернено',
                // canceled: 'Скасовано',
                // no_results: 'Немає результатів',
                loading: 'Завантаження',
                // phone_length_minimum_7_characters: 'Довжина телефону не менше 7 символів',
                // your_order_may_take_some_time_to_process: 'Обробка вашого замовлення може зайняти деякий час.',
                // sizes_table: 'Таблиця розмірів',
                // international: 'Міжнарод.',
                // chest_girth: 'Обхват грудей',
                // waist_circumference: 'Обхват талії',
                // hip_girth: 'Обхват стегон',
                load_more: 'Завантажити більше',
                // promo: 'Промо',
                // promo_options: 'Промо опції',
                // edit_promo: 'Редагувати промо',
                // add_promo: 'Додати промо',
                // available_promo: 'Доступні промо',
                // add_promo_code: 'Додати промо код',
                // promo_name: 'Назва промо',
                // add_promo_name: 'Додати назву промо',
                out_of: 'з',
                //     models: 'моделей',
                //     in_order_to_use_this_option_you_must_log_in_or_register:
                //         'Щоб скористатися цією опцією, ви повинні увійти або зареєструватися.',
                //     you_need_to_login: 'Потрібно увійти!',
                //     sended: 'Надіслано',
                //     store_key: 'Ключ магазину',
                //     enter_store_key: 'Введіть ключ магазину!',
                //     this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                //         'Цей каталог є приватним, щоб увійти необхідно ввести ключ каталогу.',
                //     this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                //         'Цей каталог не підтримує поточну мову, щоб продовжити, виберіть мову зі списку в меню мов',
                //     language_error: 'Помилка мови!',
            },
        },
    ];

    useEffect(() => {
        setCurrentLanguage(langList.find(({ code }) => code === lang));
    }, [lang]);

    return { currentLanguage };
};
