import { useEffect, useState } from 'react';

export const useGetLanguage = ({ lang }) => {
    const [currentLanguage, setCurrentLanguage] = useState({ code: '', string: {} });

    const langList = [
        {
            code: 'ua',

            string: {
                option_not_available: 'Опцiя недоступна',
                replace: 'Змiнити',
                your_limit: 'Ваш лiмiт',
                create_a_color: 'Створiть колiр',
                create_a_brand: 'Створiть бренд',
                yes: 'Так',
                no: 'Нi',
                show_in_market: 'Доступний на платформi',
                unlimited: 'Необмежено',
                call_back: 'Зворотнiй зв`язок',
                size_table: 'Таблиця розмірів',
                attached_to_the_product_deletion_is_not_possible: 'Прикріплений до продукту. Видалення неможливо',
                leave_the_comment: 'Залишити коментар',
                change_status: 'Змiнити статус',
                change: 'Змiнити',
                order_history: 'Iсторiя замовлення',
                delivery_address: 'Адреса Поштового Вiддiлення',
                company: 'Компанiя',
                total_final_price: 'Загальна сума',
                total_quantity: 'Загальна кiлькiсть',
                quantity: 'Кiлькiсть',
                final_price: 'Сумма',
                create_new_model: 'Створити нову модель',
                click_to_choose: 'натиснiть щоб обрати',
                file_more_then_ten_mbd: 'Файл бiльше 10MB',
                wrong_file_format: 'Невiрний формат файлу',
                image: 'Зображення',
                video: 'Вiдео',
                add_image: 'Додати зображення',
                examples: 'Приклади',
                add_models_before: 'Спершу додайте моделi',
                types: 'Види',
                date_available: 'Дата наявностi',
                product_type: 'Тип продукта',
                items: 'одиниць',
                find: 'Знайти',
                customers: 'Клієнти',
                customer: 'Замовник',
                delivery: 'Доставка',
                orders: 'Замовлення',
                order: 'Замовлення',
                brands: 'Бренди',
                brand: 'Бренд',
                list: 'Список',
                inventory: 'Iнвентар',
                market: 'Ринок',
                store_with_this_code_is_registered: 'Магазин з такою поштою зареєстрований',
                category_with_this_code_is_registered: 'Категорiя з таким кодом зареєстрована',
                user_with_this_email_is_registered: 'Користувач з такою поштою зареєстрований',
                brand_with_this_code_is_registered: 'Бренд з таким кодом зареєстрований',
                color_with_this_code_is_registered: 'Колiр з таким кодом вже створено',
                size_with_this_code_is_registered: 'Розмiр з таким кодом вже створено',
                promo_with_this_code_is_registered: 'Промо тег з таким кодом вже створено',
                model_with_this_vendor_code_is_registered: 'Модель з таким артикулом вже створена',
                create_user: 'Створити користувача',
                edit_user: 'Редагувати користувача',
                back: 'Назад',
                create_new_user: 'Створити нового користувача',
                should_contains_1_character_lowercase_1_character_uppercase_1_digit_6_to_12_characters:
                    'Має містити 1 символ у нижньому регістрі, 1 символ у верхньому регістрі, 1 цифру, від 6 до 12 символів',
                active: 'Активований',
                activate: 'Активувати',
                deactivate: 'Деактивувати',
                code_must_be_unique: 'Код повинен бути унiкальним',
                staff: 'Персонал',
                store_address: 'Адреса магазину',
                store_description: 'Опис магазину',
                product_settings: 'Налаштування продукцii',
                product_types: 'Типи товару',
                store_security: 'Безпека магазину',
                private_store: 'Приватний магазин',
                store_key: 'Ключ магазину',
                share_product_link: 'Подiлитися посиланням товару',
                prices: 'Цiни',
                search_by_sku: 'Пошук за артикулом',
                functions_settings: 'Налаштування функцiоналу',
                product_image_settings: 'Налаштування зображення продукту',
                logo: 'Логотип',
                store_image: 'Зображення магазину',
                width: 'Ширина',
                height: 'Висота',
                crop_width: 'Обрiзати ширину',
                crop_height: 'Обрiзати висоту',
                settings: 'Налаштування',
                images_settings: 'Налаштування зображень',
                options: 'Опції',
                add_new: 'Додати нового',
                manager: 'Менеджер',
                owner: 'Власник',
                start_date_operation: 'Дата початку роботи',
                currency: 'Валюта',
                default_language: 'Мова по замовчуванню',
                supported_languages: 'Мови магазину',
                postal_code: 'Поштовий iндекс',
                store_state_province: 'Штат/область магазину',
                store_phone: 'Телефон магазину',
                store_email: 'Електронна пошта магазину',
                store_code: 'Код магазину',
                store_name: 'Назва магазину',
                store_city: 'Мiсто магазину',
                store_country: 'Країна магазину',
                edit_store: 'Редагувати магазин',
                edit: 'Редагувати',
                create_store: 'Створити магазин',
                store: 'Магазин',
                stores_management: 'Керування магазинами',
                users: 'Користувачi',
                user: 'Користувач',
                main: 'Головна',
                create_new_store: 'Створити новий магазин',
                download_image: 'Завантажити фото',
                download_logo: 'Завантажити логотип',
                search: 'Знайти',
                approve: 'Пiдтвердити',
                clear_filters: 'Очистити фільтри',
                clear: 'Очистити',
                filter: 'Фільтр',
                nothing_was_found: 'Нічого не знайдено',
                stores: 'Магазини',
                favorites: 'Уподобане',
                login: 'Вхід',
                welcome_to_Sales_Nest_to_get_started_login:
                    'Ласкаво просимо до Sales Nest, щоб почати роботу, увійдіть!',
                wrong_login_or_password: 'Неправильний логін або пароль',
                cart: 'Кошик',
                vendor_code: 'Артикул',
                color: 'Колір',
                price: 'Ціна',
                logout: 'Вийти',
                submit: 'Підтвердити',
                ukraine: 'Україна',
                czechia: 'Чехія',
                poland: 'Польща',
                description: 'Опис',
                first_name: `Ім'я`,
                last_name: 'Прізвище',
                phone_number: 'Номер телефону',
                city: 'Місто',
                email: 'Пошта',
                password: 'Пароль',
                confirm_password: 'Підтвердити пароль',
                do_want_to_logout: 'Ви дійсно хочете залишити обліковий запис?',
                status: 'Статус',
                ordered_date: 'Дата замовлення',
                do_you_want_to_delete_promo_label: 'Хочете видалити промо тег?',
                do_you_want_to_delete_color: 'Хочете видалити колiр?',
                do_you_want_to_delete_size: 'Хочете видалити розмiр?',
                do_you_want_to_delete_store: 'Хочете видалити магазин?',
                do_you_want_to_delete_user: 'Хочете видалити кориистувача?',
                do_you_want_to_delete_product: 'Хочете видалити товар?',
                do_you_want_to_delete_brand: 'Хочете видалити бренд?',
                do_you_want_to_delete_model: 'Хочете видалити модель?',
                do_you_want_to_delete_category: 'Хочете видалити категорiю?',
                cancel: 'Скасувати',
                enter_password: 'Введіть пароль',
                enter_email: 'Введіть електронну пошту',
                enter_valid_email: 'Введіть дійсну електронну пошту',
                password_length_min_8_symbols: 'Довжина пароля не менше 8 символів',
                passwords_do_not_match: 'Паролі не збігаються',
                my_profile: 'Профіль',
                country: 'Країна',
                customers_list: 'Список клієнтів',
                categories: 'Категорії',
                colors: 'Кольори',
                sizes: 'Розміри',
                full_name: `Повне ім'я`,
                size: 'Розмір',
                save: 'Зберегти',
                saved: 'Сбережено',
                updated: 'Оновлено',
                created: 'Створено',
                deleted: 'Видалено',
                contacts: 'Контакти',
                name: 'Назва',
                create: 'Створити',
                update: 'Оновити',
                order_priority: 'Пріоритет',
                models: 'Моделі',
                model: 'Модель',
                add: 'Додати',
                delete: 'Видалити',
                create_category: 'Створити категорiю',
                choose_or_create_a_category: 'Оберiть або створiть категорiю',
                add_category: 'Додати категорію',
                label: 'Позначка',
                code: 'Код',
                products: 'Товар',
                processed: 'Обробелено',
                ordered: 'Замовлено',
                delivered: 'Доставлено',
                refunded: 'Повернено',
                canceled: 'Скасовано',
                loading: 'Завантаження',
                available: 'В наявностi',
                load_more: 'Завантажити більше',
                promo: 'Промо',
                available_in_browser: 'Доступний для браузера',
                out_of: 'з',
                photo: 'Фото',
                analytics: 'Аналiтика',
            },
        },
    ];

    useEffect(() => {
        setCurrentLanguage(langList.find(({ code }) => code === lang));
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [lang]);

    return { currentLanguage };
};
