export const STORES_DATA = [
    {
        code: 'SKIPPER', // skipper ремни черновцы на удаление
        webUrl: 'https://skipper-belts.netlify.app',
        appStoreUrl: '',
        playMarketUrl: '',
        mainImage: require('./images/belts.jpeg'),
        productImagesOptions: { width: 6, height: 7.5, cropX: 0, cropY: 30 },
        descriptions: [
            {
                language: 'ua',
                name: 'Skipper',
                description: 'Магазин ременiв',
                friendlyUrl: 'Магазин ременiв',
                keyWords: 'Магазин ременiв',
                highlights: 'Магазин ременiв',
                metaDescription: 'Магазин ременiв',
                title: 'Магазин ременiв',
            },
            {
                language: 'en',
                name: 'Skipper',
                description: 'Belts Store',
                friendlyUrl: 'Belts Store',
                keyWords: 'Belts Store',
                highlights: 'Belts Store',
                metaDescription: 'Belts Store',
                title: 'Store of Belts',
            },
            {
                language: 'pl',
                name: 'Skipper',
                description: 'Sklep z paskami',
                friendlyUrl: 'Sklep z paskami',
                keyWords: 'Sklep z paskami',
                highlights: 'Sklep z paskami',
                metaDescription: 'Sklep z paskami',
                title: 'Sklep z paskami skórzanymi i akcesoriami',
            },
        ],
        mainStoreSettings: {
            withTranslator: false,
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: false,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
            platformAvailable: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: false,
            callback: false,
            appleStore: false,
            playMarket: false,
            analytics: false,
        },
        dataBaseStoreSettings: {
            users: 2,
            products: 50,
            productModels: 5,
            photos: 5,
            videos: 1,
        },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [{ code: 'Men clothes' }, { code: 'Women clothes' }, { code: 'Belts' }],
        managers: [
            {
                firstName: 'Sergey',
                lastName: '',
                emailAddress: '',
                options: { manager: true },
                contacts: {
                    emailAddress: 'skipperbelts@ukr.net',
                    phone: '+380502399733',
                    viber: '+380502399733',
                    whatsapp: '+380502399733',
                    telegram: '',
                },
            },
        ],
    },
    {
        code: 'DEFAULT', // kremen-belts main
        webUrl: 'https://kremen-belts.netlify.app',
        appStoreUrl: '',
        playMarketUrl: '',
        mainImage: require('./images/belts.jpeg'),
        productImagesOptions: { width: 4, height: 3, cropX: 0, cropY: 0 },
        descriptions: [
            {
                language: 'ua',
                name: 'Кремен Белтс',
                description: 'Магазин ременiв',
                friendlyUrl: 'Магазин ременiв',
                keyWords: 'Магазин ременiв',
                highlights: 'Магазин ременiв',
                metaDescription: 'Магазин ременiв',
                title: 'Магазин ременiв',
            },
            {
                language: 'en',
                name: 'Kremen Belts',
                description: 'Belts Store',
                friendlyUrl: 'Belts Store',
                keyWords: 'Belts Store',
                highlights: 'Belts Store',
                metaDescription: 'Belts Store',
                title: 'Store of Belts',
            },
            {
                language: 'ru',
                name: 'Кремень Белтс',
                description: 'Магазин ремней',
                friendlyUrl: 'Магазин ремней',
                keyWords: 'Магазин ремней',
                highlights: 'Магазин ремней',
                metaDescription: 'Магазин ремней',
                title: 'Магазин ремней и аксессуаров из кожи',
            },
        ],
        mainStoreSettings: {
            withTranslator: false,
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: false,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
            platformAvailable: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: false,
            callback: false,
            appleStore: false,
            playMarket: false,
            analytics: false,
        },
        dataBaseStoreSettings: {
            users: 'unlimited',
            products: 'unlimited',
            productModels: 'unlimited',
            photos: 10,
            videos: 1,
        },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [{ code: 'Men clothes' }, { code: 'Women clothes' }, { code: 'Belts' }],
        managers: [
            {
                firstName: 'Sergey',
                lastName: '',
                emailAddress: 'Kremen.katalog@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'Kremen.katalog@gmail.com',
                    phone: '+380660355716',
                    viber: '+380660355716',
                    whatsapp: '+380660355716',
                    telegram: '',
                },
            },
        ],
    },
    {
        code: 'kremen_belts_sales', // kremen-belts-sales
        webUrl: 'https://kremen-belts-sales.netlify.app/',
        appStoreUrl: '',
        playMarketUrl: '',
        mainImage: require('./images/belts.jpeg'),
        productImagesOptions: { width: 3, height: 2, cropX: 0, cropY: 0 },
        descriptions: [
            {
                language: 'ua',
                name: 'Кремен Белтс',
                description: 'Магазин ременiв',
                friendlyUrl: 'Магазин ременiв',
                keyWords: 'Магазин ременiв',
                highlights: 'Магазин ременiв',
                metaDescription: 'Магазин ременiв',
                title: 'Магазин ременiв',
            },
            // {
            //     language: 'en',
            //     name: 'Kremen Belts',
            //     description: 'Belts Store',
            //     friendlyUrl: 'Belts Store',
            //     keyWords: 'Belts Store',
            //     highlights: 'Belts Store',
            //     metaDescription: 'Belts Store',
            //     title: 'Store of Belts',
            // },
            // {
            //     language: 'ru',
            //     name: 'Кремень Белтс',
            //     description: 'Магазин ремней',
            //     friendlyUrl: 'Магазин ремней',
            //     keyWords: 'Магазин ремней',
            //     highlights: 'Магазин ремней',
            //     metaDescription: 'Магазин ремней',
            //     title: 'Магазин ремней и аксессуаров из кожи',
            // },
        ],
        mainStoreSettings: {
            withTranslator: false,
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: false,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
            platformAvailable: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: false,
            callback: false,
            appleStore: false,
            playMarket: false,
            analytics: false,
        },
        dataBaseStoreSettings: {
            users: 3,
            products: 200,
            productModels: 10,
            photos: 5,
            videos: 1,
        },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [{ code: 'Men clothes' }, { code: 'Women clothes' }, { code: 'Belts' }],
        managers: [
            {
                firstName: 'Sergey',
                lastName: '',
                emailAddress: 'Kremen.katalog@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'Kremen.katalog@gmail.com',
                    phone: '+380660355716',
                    viber: '+380660355716',
                    whatsapp: '+380660355716',
                    telegram: '',
                },
            },
        ],
    },
    {
        code: 'ALBERTO_BINI_SALES',
        appStoreUrl: '',
        playMarketUrl: '',
        webUrl: 'https://alberto-bini-sales.netlify.app',
        mainImage: require('./images/alb.jpeg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 20 },
        descriptions: [
            {
                language: 'ua',
                name: 'Магазин жiночого одягу',
                description: 'Магазин жiночого одягу',
                friendlyUrl: 'Магазин жiночого одягу',
                keyWords: 'Магазин жiночого одягу',
                highlights: 'Магазин жiночого одягу',
                metaDescription: 'Магазин жiночого одягу',
                title: 'Магазин жiночого одягу',
            },
            {
                language: 'en',
                name: 'Store of Women`s Clothes',
                description: 'Store of Women`s Clothes',
                friendlyUrl: 'Store of Women`s Clothes',
                keyWords: 'Store of Women`s Clothes',
                highlights: 'Store of Women`s Clothes',
                metaDescription: 'Store of Women`s Clothes',
                title: 'Store of Women`s Clothes',
            },
        ],
        mainStoreSettings: {
            withTranslator: false,
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: true,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
            analytics: false,
        },
        dataBaseStoreSettings: { users: 5, products: 200, productModels: 20, photos: 20, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Outerwear',
            },
            {
                code: 'Women clothes',
            },
        ],
        managers: [
            {
                firstName: 'Elena',
                lastName: '',
                emailAddress: 'lena@admin.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'lena@admin.com',
                    phone: '+380983080085',
                    viber: '+380983080085',
                    whatsapp: '+380983080085',
                    telegram: 'Albertobiniopt',
                },
            },
        ],
    },
    {
        code: 'ArcticStoryFurs', //на удаление
        appStoreUrl: '',
        playMarketUrl: '',
        webUrl: 'https://arctic-story-furs.netlify.app',
        mainImage: require('./images/bags.jpeg'),
        productImagesOptions: { width: 6, height: 9, cropX: 0, cropY: 15 },
        descriptions: [
            {
                language: 'ua',
                name: 'Arctic Story Furs',
                description: 'Магазин жiночого одягу',
                friendlyUrl: 'Магазин жiночого одягу',
                keyWords: 'Магазин жiночого одягу',
                highlights: 'Магазин жiночого одягу',
                metaDescription: 'Магазин жiночого одягу',
                title: 'Магазин жiночого одягу',
            },
            {
                language: 'pl',
                name: 'Arctic Story Furs',
                description: 'Sklep z odzieżą damską',
                friendlyUrl: 'Sklep z odzieżą damską',
                keyWords: 'Sklep z odzieżą damską',
                highlights: 'Sklep z odzieżą damską',
                metaDescription: 'Sklep z odzieżą damską',
                title: 'Sklep z odzieżą damską',
            },
            {
                language: 'en',
                name: 'Arctic Story Furs',
                description: 'Store of Women`s Clothes',
                friendlyUrl: 'Store of Women`s Clothes',
                keyWords: 'Store of Women`s Clothes',
                highlights: 'Store of Women`s Clothes',
                metaDescription: 'Store of Women`s Clothes',
                title: 'Store of Women`s Clothes',
            },
            {
                language: 'ru',
                name: 'Arctic Story Furs',
                description: 'Магазин Женской Одежды',
                friendlyUrl: 'Магазин Женской Одежды',
                keyWords: 'Магазин Женской Одежды',
                highlights: 'Магазин Женской Одежды',
                metaDescription: 'Магазин Женской Одежды',
                title: 'Магазин Женской Одежды',
            },
        ],
        mainStoreSettings: {
            withTranslator: false,
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: false,
            callback: true,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
            analytics: true,
        },
        dataBaseStoreSettings: { users: 2, products: 200, productModels: 10, photos: 10, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Outerwear',
            },
            {
                code: 'Women clothes',
            },
        ],
        managers: [
            {
                firstName: 'Сергей',
                lastName: 'Коптюх',
                emailAddress: 'koptiukh2015@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'koptiukh2015@gmail.com',
                    phone: '+380665607580',
                    viber: '+380665607580',
                    whatsapp: '+380665607580',
                    telegram: 'koptiukhsergey',
                },
            },
        ],
    },
    {
        code: 'ALBERTO_BINI', //alberto bini main
        appStoreUrl: '',
        playMarketUrl: '',
        webUrl: 'https://alberto-bini.netlify.app',
        mainImage: require('./images/alb.jpeg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 20 },
        descriptions: [
            {
                language: 'ua',
                name: 'Магазин жiночого одягу',
                description: 'Магазин жiночого одягу',
                friendlyUrl: 'Магазин жiночого одягу',
                keyWords: 'Магазин жiночого одягу',
                highlights: 'Магазин жiночого одягу',
                metaDescription: 'Магазин жiночого одягу',
                title: 'Магазин жiночого одягу',
            },
            {
                language: 'en',
                name: 'Store of Women`s Clothes',
                description: 'Store of Women`s Clothes',
                friendlyUrl: 'Store of Women`s Clothes',
                keyWords: 'Store of Women`s Clothes',
                highlights: 'Store of Women`s Clothes',
                metaDescription: 'Store of Women`s Clothes',
                title: 'Store of Women`s Clothes',
            },
        ],
        mainStoreSettings: {
            withTranslator: false,
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: true,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
            analytics: true,
        },
        dataBaseStoreSettings: { users: 5, products: 200, productModels: 20, photos: 20, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Outerwear',
            },
            {
                code: 'Women clothes',
            },
        ],
        managers: [
            {
                firstName: 'Elena',
                lastName: '',
                emailAddress: 'alb-admin@mail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'alb-admin@mail.com',
                    phone: '+380983080085',
                    viber: '+380983080085',
                    whatsapp: '+380983080085',
                    telegram: 'Albertobiniopt',
                },
            },
        ],
    },
    {
        code: 'alberto_bini_europe', // на рекламу европа казахстан 'https://albertobini-kz.com'
        appStoreUrl: '',
        playMarketUrl: '',
        webUrl: 'https://albertobini-brandeurope.com',
        mainImage: require('./images/alb.jpeg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 20 },
        descriptions: [
            {
                language: 'en',
                name: 'Store of Women`s Clothes',
                description: 'Store of Women`s Clothes',
                friendlyUrl: 'Store of Women`s Clothes',
                keyWords: 'Store of Women`s Clothes',
                highlights: 'Store of Women`s Clothes',
                metaDescription: 'Store of Women`s Clothes',
                title: 'Store of Women`s Clothes',
            },
            {
                language: 'kz',
                name: 'Магазин Женской Одежды',
                description: 'Магазин Женской Одежды',
                friendlyUrl: 'Магазин Женской Одежды',
                keyWords: 'Магазин Женской Одежды',
                highlights: 'Магазин Женской Одежды',
                metaDescription: 'Магазин Женской Одежды',
                title: 'Магазин Женской Одежды',
            },
        ],
        mainStoreSettings: {
            withTranslator: false,
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
            analytics: false,
        },
        dataBaseStoreSettings: { users: 5, products: 200, productModels: 10, photos: 10, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Outerwear',
            },
            {
                code: 'Women clothes',
            },
        ],
        managers: [
            {
                firstName: 'Alberto Bini Manager',
                lastName: '',
                emailAddress: 'salesnest.info@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'salesnest.info@gmail.com',
                    phone: '+380983080085',
                    viber: '+380983080085',
                    whatsapp: '+380983080085',
                    telegram: 'SNBusinessApp',
                },
            },
        ],
    },

    // COCKTAIL FABRIC STORES

    {
        code: 'albertobini_retailer', //alberto bini retailer mine
        appStoreUrl: '',
        playMarketUrl: '',
        webUrl: 'https://albertobini-brandeurope.com',
        mainImage: require('./images/alb.jpeg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 20 },
        descriptions: [
            {
                language: 'ua',
                name: 'Магазин жiночого одягу',
                description: 'Магазин жiночого одягу',
                friendlyUrl: 'Магазин жiночого одягу',
                keyWords: 'Магазин жiночого одягу',
                highlights: 'Магазин жiночого одягу',
                metaDescription: 'Магазин жiночого одягу',
                title: 'Магазин жiночого одягу',
            },
            {
                language: 'en',
                name: 'Store of Women`s Clothes',
                description: 'Store of Women`s Clothes',
                friendlyUrl: 'Store of Women`s Clothes',
                keyWords: 'Store of Women`s Clothes',
                highlights: 'Store of Women`s Clothes',
                metaDescription: 'Store of Women`s Clothes',
                title: 'Store of Women`s Clothes',
            },
        ],
        mainStoreSettings: {
            withTranslator: false,
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: true,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
            analytics: true,
        },
        dataBaseStoreSettings: { users: 5, products: 200, productModels: 20, photos: 20, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Outerwear',
            },
            {
                code: 'Women clothes',
            },
        ],
        managers: [
            {
                firstName: 'Manager',
                lastName: '',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380668652127',
                    viber: '+380668652127',
                    whatsapp: '+380668652127',
                    telegram: 'SNBusinessApp',
                },
            },
        ],
    },

    {
        code: 'burda_style', //alberto bini retailer mine
        appStoreUrl: '',
        playMarketUrl: '',
        webUrl: 'https://cocktaile-fabric.com',
        mainImage: require('./images/burda_style.jpg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 20 },
        descriptions: [
            {
                language: 'ua',
                name: 'Магазин жiночого одягу',
                description: 'Магазин жiночого одягу',
                friendlyUrl: 'Магазин жiночого одягу',
                keyWords: 'Магазин жiночого одягу',
                highlights: 'Магазин жiночого одягу',
                metaDescription: 'Магазин жiночого одягу',
                title: 'Магазин жiночого одягу',
            },
            {
                language: 'en',
                name: 'Store of Women`s Clothes',
                description: 'Store of Women`s Clothes',
                friendlyUrl: 'Store of Women`s Clothes',
                keyWords: 'Store of Women`s Clothes',
                highlights: 'Store of Women`s Clothes',
                metaDescription: 'Store of Women`s Clothes',
                title: 'Store of Women`s Clothes',
            },
        ],
        mainStoreSettings: {
            withTranslator: false,
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
            analytics: true,
        },
        dataBaseStoreSettings: { users: 5, products: 200, productModels: 20, photos: 20, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Outerwear',
            },
            {
                code: 'Women clothes',
            },
        ],
        managers: [
            {
                firstName: 'Manager',
                lastName: '',
                emailAddress: 'salesnest.info@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'salesnest.info@gmail.com',
                    phone: '+380668652127',
                    viber: '+380668652127',
                    whatsapp: '+380668652127',
                    telegram: 'SNBusinessApp',
                },
            },
        ],
    },
    {
        code: 'pasma_design', //alberto bini retailer mine
        appStoreUrl: '',
        playMarketUrl: '',
        webUrl: 'https://cocktaile-fabric.com',
        mainImage: require('./images/burda_style.jpg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 20 },
        descriptions: [
            {
                language: 'ua',
                name: 'Магазин жiночого одягу',
                description: 'Магазин жiночого одягу',
                friendlyUrl: 'Магазин жiночого одягу',
                keyWords: 'Магазин жiночого одягу',
                highlights: 'Магазин жiночого одягу',
                metaDescription: 'Магазин жiночого одягу',
                title: 'Магазин жiночого одягу',
            },
            {
                language: 'en',
                name: 'Store of Women`s Clothes',
                description: 'Store of Women`s Clothes',
                friendlyUrl: 'Store of Women`s Clothes',
                keyWords: 'Store of Women`s Clothes',
                highlights: 'Store of Women`s Clothes',
                metaDescription: 'Store of Women`s Clothes',
                title: 'Store of Women`s Clothes',
            },
        ],
        mainStoreSettings: {
            withTranslator: false,
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
            analytics: true,
        },
        dataBaseStoreSettings: { users: 5, products: 200, productModels: 20, photos: 20, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Outerwear',
            },
            {
                code: 'Women clothes',
            },
        ],
        managers: [
            {
                firstName: 'Manager',
                lastName: '',
                emailAddress: 'salesnest.info@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'salesnest.info@gmail.com',
                    phone: '+380668652127',
                    viber: '+380668652127',
                    whatsapp: '+380668652127',
                    telegram: 'SNBusinessApp',
                },
            },
        ],
    },
    {
        code: 'sandra', //alberto bini retailer mine
        appStoreUrl: '',
        playMarketUrl: '',
        webUrl: 'https://sandra.com',
        mainImage: require('./images/alb.jpeg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 20 },
        descriptions: [
            {
                language: 'ua',
                name: 'Магазин жiночого одягу',
                description: 'Магазин жiночого одягу',
                friendlyUrl: 'Магазин жiночого одягу',
                keyWords: 'Магазин жiночого одягу',
                highlights: 'Магазин жiночого одягу',
                metaDescription: 'Магазин жiночого одягу',
                title: 'Магазин жiночого одягу',
            },
            {
                language: 'en',
                name: 'Store of Women`s Clothes',
                description: 'Store of Women`s Clothes',
                friendlyUrl: 'Store of Women`s Clothes',
                keyWords: 'Store of Women`s Clothes',
                highlights: 'Store of Women`s Clothes',
                metaDescription: 'Store of Women`s Clothes',
                title: 'Store of Women`s Clothes',
            },
        ],
        mainStoreSettings: {
            withTranslator: false,
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
            analytics: true,
        },
        dataBaseStoreSettings: { users: 5, products: 200, productModels: 20, photos: 20, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Outerwear',
            },
            {
                code: 'Women clothes',
            },
        ],
        managers: [
            {
                firstName: 'Manager',
                lastName: '',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380668652127',
                    viber: '+380668652127',
                    whatsapp: '+380668652127',
                    telegram: 'SNBusinessApp',
                },
            },
        ],
    },
    {
        code: 'igle_store',
        appStoreUrl: '',
        playMarketUrl: '',
        webUrl: 'https://igle.com',
        mainImage: require('./images/alb.jpeg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 20 },
        descriptions: [
            {
                language: 'ua',
                name: 'Магазин жiночого одягу',
                description: 'Магазин жiночого одягу',
                friendlyUrl: 'Магазин жiночого одягу',
                keyWords: 'Магазин жiночого одягу',
                highlights: 'Магазин жiночого одягу',
                metaDescription: 'Магазин жiночого одягу',
                title: 'Магазин жiночого одягу',
            },
            {
                language: 'en',
                name: 'Store of Women`s Clothes',
                description: 'Store of Women`s Clothes',
                friendlyUrl: 'Store of Women`s Clothes',
                keyWords: 'Store of Women`s Clothes',
                highlights: 'Store of Women`s Clothes',
                metaDescription: 'Store of Women`s Clothes',
                title: 'Store of Women`s Clothes',
            },
        ],
        mainStoreSettings: {
            withTranslator: false,
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
            analytics: true,
        },
        dataBaseStoreSettings: { users: 5, products: 200, productModels: 20, photos: 20, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Outerwear',
            },
            {
                code: 'Women clothes',
            },
        ],
        managers: [
            {
                firstName: 'Manager',
                lastName: '',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380668652127',
                    viber: '+380668652127',
                    whatsapp: '+380668652127',
                    telegram: 'SNBusinessApp',
                },
            },
        ],
    },
    {
        code: 'you_best',
        appStoreUrl: '',
        playMarketUrl: '',
        webUrl: 'https://you-best.com',
        mainImage: require('./images/alb.jpeg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 20 },
        descriptions: [
            {
                language: 'ua',
                name: 'Магазин жiночого одягу',
                description: 'Магазин жiночого одягу',
                friendlyUrl: 'Магазин жiночого одягу',
                keyWords: 'Магазин жiночого одягу',
                highlights: 'Магазин жiночого одягу',
                metaDescription: 'Магазин жiночого одягу',
                title: 'Магазин жiночого одягу',
            },
            {
                language: 'en',
                name: 'Store of Women`s Clothes',
                description: 'Store of Women`s Clothes',
                friendlyUrl: 'Store of Women`s Clothes',
                keyWords: 'Store of Women`s Clothes',
                highlights: 'Store of Women`s Clothes',
                metaDescription: 'Store of Women`s Clothes',
                title: 'Store of Women`s Clothes',
            },
        ],
        mainStoreSettings: {
            withTranslator: false,
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
            analytics: true,
        },
        dataBaseStoreSettings: { users: 5, products: 200, productModels: 20, photos: 20, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Outerwear',
            },
            {
                code: 'Women clothes',
            },
        ],
        managers: [
            {
                firstName: 'Manager',
                lastName: '',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380668652127',
                    viber: '+380668652127',
                    whatsapp: '+380668652127',
                    telegram: 'SNBusinessApp',
                },
            },
        ],
    },
    {
        code: 'cocktail_store',
        appStoreUrl: '',
        playMarketUrl: '',
        webUrl: '',
        mainImage: require('./images/alb.jpeg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 20 },
        descriptions: [
            {
                language: 'ua',
                name: 'Магазин жiночого одягу',
                description: 'Магазин жiночого одягу',
                friendlyUrl: 'Магазин жiночого одягу',
                keyWords: 'Магазин жiночого одягу',
                highlights: 'Магазин жiночого одягу',
                metaDescription: 'Магазин жiночого одягу',
                title: 'Магазин жiночого одягу',
            },
            {
                language: 'en',
                name: 'Store of Women`s Clothes',
                description: 'Store of Women`s Clothes',
                friendlyUrl: 'Store of Women`s Clothes',
                keyWords: 'Store of Women`s Clothes',
                highlights: 'Store of Women`s Clothes',
                metaDescription: 'Store of Women`s Clothes',
                title: 'Store of Women`s Clothes',
            },
        ],
        mainStoreSettings: {
            withTranslator: false,
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
            analytics: true,
        },
        dataBaseStoreSettings: { users: 5, products: 200, productModels: 20, photos: 20, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Outerwear',
            },
            {
                code: 'Women clothes',
            },
        ],
        managers: [
            {
                firstName: 'Manager',
                lastName: '',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380668652127',
                    viber: '+380668652127',
                    whatsapp: '+380668652127',
                    telegram: 'SNBusinessApp',
                },
            },
        ],
    },
    {
        code: 'hm',
        appStoreUrl: '',
        playMarketUrl: '',
        webUrl: '',
        mainImage: require('./images/alb.jpeg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 20 },
        descriptions: [
            {
                language: 'ua',
                name: 'Магазин жiночого одягу',
                description: 'Магазин жiночого одягу',
                friendlyUrl: 'Магазин жiночого одягу',
                keyWords: 'Магазин жiночого одягу',
                highlights: 'Магазин жiночого одягу',
                metaDescription: 'Магазин жiночого одягу',
                title: 'Магазин жiночого одягу',
            },
            {
                language: 'en',
                name: 'Store of Women`s Clothes',
                description: 'Store of Women`s Clothes',
                friendlyUrl: 'Store of Women`s Clothes',
                keyWords: 'Store of Women`s Clothes',
                highlights: 'Store of Women`s Clothes',
                metaDescription: 'Store of Women`s Clothes',
                title: 'Store of Women`s Clothes',
            },
        ],
        mainStoreSettings: {
            withTranslator: false,
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
            analytics: true,
        },
        dataBaseStoreSettings: { users: 5, products: 200, productModels: 20, photos: 20, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Outerwear',
            },
            {
                code: 'Women clothes',
            },
        ],
        managers: [
            {
                firstName: 'Manager',
                lastName: '',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380668652127',
                    viber: '+380668652127',
                    whatsapp: '+380668652127',
                    telegram: 'SNBusinessApp',
                },
            },
        ],
    },
    {
        code: 'sassofono',
        appStoreUrl: '',
        playMarketUrl: '',
        webUrl: '',
        mainImage: require('./images/alb.jpeg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 20 },
        descriptions: [
            {
                language: 'ua',
                name: 'Магазин жiночого одягу',
                description: 'Магазин жiночого одягу',
                friendlyUrl: 'Магазин жiночого одягу',
                keyWords: 'Магазин жiночого одягу',
                highlights: 'Магазин жiночого одягу',
                metaDescription: 'Магазин жiночого одягу',
                title: 'Магазин жiночого одягу',
            },
            {
                language: 'en',
                name: 'Store of Women`s Clothes',
                description: 'Store of Women`s Clothes',
                friendlyUrl: 'Store of Women`s Clothes',
                keyWords: 'Store of Women`s Clothes',
                highlights: 'Store of Women`s Clothes',
                metaDescription: 'Store of Women`s Clothes',
                title: 'Store of Women`s Clothes',
            },
        ],
        mainStoreSettings: {
            withTranslator: false,
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
            analytics: true,
        },
        dataBaseStoreSettings: { users: 5, products: 200, productModels: 20, photos: 20, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Outerwear',
            },
            {
                code: 'Women clothes',
            },
        ],
        managers: [
            {
                firstName: 'Manager',
                lastName: '',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380668652127',
                    viber: '+380668652127',
                    whatsapp: '+380668652127',
                    telegram: 'SNBusinessApp',
                },
            },
        ],
    },
    {
        code: 'stoned_club',
        appStoreUrl: '',
        playMarketUrl: '',
        webUrl: '',
        mainImage: null,
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 20 },
        descriptions: [
            {
                language: 'ua',
                name: 'Stoned Club',
                description: 'Магазин',
                friendlyUrl: 'Магазин',
                keyWords: 'Магазин',
                highlights: 'Магазин',
                metaDescription: 'Магазин',
                title: 'Магазин',
            },
            {
                language: 'ru',
                name: 'Stoned Club',
                description: 'Магазин',
                friendlyUrl: 'Магазин',
                keyWords: 'Магазин',
                highlights: 'Магазин',
                metaDescription: 'Магазин',
                title: 'Магазин',
            },
        ],
        mainStoreSettings: {
            withTranslator: false,
            skuSearch: true,
            colors: false,
            prices: true,
            sizes: false,
            contacts: true,
            categories: true,
            browserSearch: false,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: true,
            tableSizes: false,
            callback: false,
            platformAvailable: false,
            appleStore: false,
            playMarket: false,
            analytics: true,
        },
        dataBaseStoreSettings: { users: 5, products: 1000, productModels: 20, photos: 20, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [],
        managers: [
            {
                firstName: 'Manager',
                lastName: '',
                emailAddress: 'manager8@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'manager8@gmail.com',
                    phone: '+380000000000',
                    viber: '+380000000000',
                    whatsapp: '+380000000000',
                    telegram: null,
                },
            },
        ],
    },
];
